packages:
  - packages/**

catalog:
  '@eslint/js': ^9.37.0
  '@stylistic/eslint-plugin': ^5.4.0
  '@tsconfig/node22': 22.0.2
  '@types/cors': ^2.8.19
  '@types/eslint': ^9.6.1
  '@types/express': ^5.0.3
  '@types/lodash-es': ^4.17.12
  '@types/node': 22.16.5
  '@typescript-eslint/parser': ^8.46.0
  '@typescript-eslint/types': ^8.46.0
  '@typescript-eslint/utils': ^8.46.0
  chalk: ^5.6.2
  ci-info: ^4.3.1
  cors: ^2.8.5
  dotenv: ^17.2.3
  eslint: 9.37.0
  eslint-plugin-import: ^2.32.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.0
  eslint-plugin-react-refresh: ^0.4.23
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-unicorn: ^61.0.2
  eslint-plugin-unused-imports: ^4.2.0
  eslint-plugin-vue: ^10.5.0
  express: ^5.1.0
  globals: ^16.4.0
  helmet: ^8.1.0
  json-colorizer: ^3.0.1
  lodash-es: ^4.17.21
  rimraf: ^6.0.1
  safe-stable-stringify: ^2.5.0
  tsx: ^4.20.6
  typescript: ^5.9.3
  typescript-eslint: ^8.46.0
  winston: ^3.18.3
  zod: ^4.1.12

catalogMode: prefer

cleanupUnusedCatalogs: true

injectWorkspacePackages: true

nodeVersion: 22.18.0

onlyBuiltDependencies:
  - esbuild

useNodeVersion: 22.18.0
